set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" Plugins
Plugin 'tpope/vim-fugitive'
Plugin 'L9'
Plugin 'git://git.wincent.com/command-t.git'
Plugin 'rstacruz/sparkup', {'rtp': 'vim/'}
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-surround'
Plugin 'pangloss/vim-javascript'
Plugin 'maksimr/vim-jsbeautify'
Plugin 'ervandew/supertab'
Plugin 'VimClojure'
Plugin 'guns/vim-clojure-static'
Plugin 'suan/vim-instant-markdown'
Plugin 'tpope/vim-markdown'
Plugin 'othree/html5.vim'
Plugin 'hsanson/vim-android'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" editor settings
syntax on
set number
set hlsearch
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
autocmd BufNewFile,BufReadPost *.md set filetype=markdown
autocmd Filetype java setlocal omnifunc=javacomplete#cComplete
let g:SuperTabDefaultCompletionType = "\<c-x>\<c-o>"
