set nocompatible              " be iMproved, required
filetype off                  " required

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'gmarik/Vundle.vim'

" Plugins
Plugin 'scrooloose/nerdtree'
Plugin 'suan/vim-instant-markdown'
Plugin 'tpope/vim-markdown'

" All of your Plugins must be added before the following line
call vundle#end()            " required
filetype plugin indent on    " required

" editor settings
syntax on
set number
set hlsearch
set smartindent
set tabstop=4
set shiftwidth=4
set expandtab
autocmd BufNewFile,BufReadPost *.md set filetype=markdown
autocmd Filetype java setlocal omnifunc=javacomplete#cComplete
let g:SuperTabDefaultCompletionType = "\<c-x>\<c-o>"
